CREATE TABLE tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  due_date DATETIME NOT NULL,
  topic TEXT NOT NULL,
  status TEXT CHECK(status IN ('TODO','IN_PROGRESS','COMPLETE')) NOT NULL DEFAULT 'TODO',
  archived INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
