DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS topics;

CREATE TABLE topics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  topic_id INTEGER NOT NULL,
  due_date TEXT NOT NULL,
  status TEXT DEFAULT 'TODO',
  archived INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (topic_id) REFERENCES topics(id)
);
